---
title: "Shapefiles"
author: "Magali Blanco"
date: "1/17/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, 
                      cache=T, cache.comments = F, 
                      message = F, warning = F, 
                      tidy.opts=list(width.cutoff=60), tidy=TRUE,
                      fig.height = 8, fig.width = 8
                      )  

# Clear workspace of all objects and unload all extra (non-base) packages
rm(list = ls(all = TRUE))
if (!is.null(sessionInfo()$otherPkgs)) {
  res <- suppressWarnings(
    lapply(paste('package:', names(sessionInfo()$otherPkgs), sep=""),
      detach, character.only=TRUE, unload=TRUE, force=TRUE))
}

pacman::p_load(knitr, kableExtra,
               # GIS
               sf,rgdal,
               #? may be required by fortify?
               maptools,
               #ggpubr, 
               tidyverse  
               )    
 

```
 
Monitoring area

```{r}
# get shapefile
#rgdal::readOGR(file.path("..", "Mobile Monitoring", "GIS", "driving regions selected", "driving_regions_selected.shp")) 

monitoring_area <- rgdal::readOGR(file.path("..",  "GIS", "Shapefiles", "Study Area", "monitoring_area_filled_in_land.shp")) 
  
# make df
monitoring_area_df <- fortify(monitoring_area)

```
 
Study area (buffered monitoring area)

```{r}
study_area <- rgdal::readOGR(file.path("..",  "GIS", "Shapefiles", "Study Area", "oval_around_monitoring_area_land.shp")) 
  
# make df
study_area_df <- fortify(study_area) 

#saveRDS(study_area_df, file = file.path("Data", "GIS", "study_area_df.rda"))

```

Spatiotemporal modeling area

```{r}
st_area <- rgdal::readOGR(file.path("..",  "GIS", "Shapefiles", "Study Area","Spatiotemporal", "st_area_land.shp")) 
  
# make df
st_area_df <- fortify(st_area)  
   
#saveRDS(st_area_df, file = file.path("Data", "GIS", "st_area_df.rda"))

```



? Routes
```{r}
#GIS/routes 190910/All routes.shp 
routes <- rgdal::readOGR(file.path("..",  "GIS", "Shapefiles", "Routes 190910", "All routes.shp")) 
  
# make df
routes_df <- fortify(routes)


```

Hx Emissions (with attributes table)

```{r}
# tutorial on how to do keep a shapefile's atrribute table in the new df created: https://rpubs.com/huanfaChen/ggplotShapefile 
# uplaod shapefile
shp <- rgdal::readOGR(file.path("..",  "GIS", "Shapefiles", "Other features", "Roads", "Traffic Sections", "2005_TPTTrafficSections", "Emissions2.shp")) 

#create unique ID for each row in the shapefile
shp@data <- shp@data %>%
  mutate(id = row.names(.)) %>%
  #make factors to characters to numbers. Note, going from a factor to a number produces numerical versions of the factor (WRONG)
  mutate_at(vars(contains(c("_g_", "AADT")), cat, OBJECTID, hw_row_no), 
            ~as.numeric(as.character(.)))  

# make shp into a df. note, this does not save all of the attributes.
shp_df <- fortify(shp) %>%  # could also use: broom::tidy(shp,region = "id")
  # add attributes back in from the shapefile
  left_join(shp@data, by = c("id"="id")) 



```


 

 
 
Save datasets.

```{r}

# saveRDS(monitoring_area_df, file = file.path("Data", "GIS", "monitoring_area_df.rda"))
# saveRDS(study_area_df, file = file.path("Data", "GIS", "study_area_df.rda"))
# saveRDS(st_area_df, file = file.path("Data", "GIS", "st_area_df.rda"))
# saveRDS(routes_df, file = file.path("Data", "GIS", "routes_df.rda"))
# saveRDS(shp_df, file = file.path("Data", "GIS", "emissions_df.rda"))

```

 