---
title: "Hx Vehicle Counts"
author: "Magali Blanco"
date: ' `r Sys.Date()` '
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, cache=T, cache.comments = F, message = F, warning = F, tidy.opts=list(width.cutoff=60), tidy=TRUE, fig.height = 8)  

# Clear workspace of all objects and unload all extra (non-base) packages
rm(list = ls(all = TRUE))
if (!is.null(sessionInfo()$otherPkgs)) {
  res <- suppressWarnings(
    lapply(paste('package:', names(sessionInfo()$otherPkgs), sep=""),
      detach, character.only=TRUE, unload=TRUE, force=TRUE))
}

pacman::p_load(dplyr, tidyverse, chron, knitr)  #chronn: is.holiday, is.weekend

#set plot theme
theme_set(theme_linedraw() + theme(legend.position="bottom")) 

```

```{r}
traffic <- read.csv(file.path("Data", "Aim 3", "historic-traffic-volumes.csv")) %>%
  filter(Year >= 1990) %>%
  select(Year, AADT, Latitude, Longitude) %>% 
  #group into 5-yr intervals since there is a lot of missing data
  mutate(Yr_grp = ifelse(Year >= 1990 & Year <= 1994, 1990,
                         ifelse(Year >= 1995 & Year <= 1999, 1995, 
                                ifelse(Year >= 2000 & Year <= 2004, 2000,
                                       ifelse(Year >= 2005 & Year <= 2009, 2005,
                                       ifelse(Year >= 2010 & Year <= 2014, 2010, 2015
                                              )))))
  )
          
  
traffic.wide <- traffic %>%
  group_by(Yr_grp, Latitude, Longitude) %>%  
  #some years have multiple readings at the same location - counters across the road? take avg to get 1 estimate
  summarize(AADT = mean(AADT)) %>%
  spread(Yr_grp, AADT)  
   
traffic.comp <- traffic.wide %>%
  drop_na()

#write.csv(traffic.comp, "hx.traffic.counts.csv", row.names = F)


```

 