---
title: "Aim 1 Power Calculation"
author: "Magali Blanco"
date: "4/2/2019"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

rm(list = ls(all = TRUE))
if (!is.null(sessionInfo()$otherPkgs)) {
  res <- suppressWarnings(
    lapply(paste('package:', names(sessionInfo()$otherPkgs), sep=""),
      detach, character.only=TRUE, unload=TRUE, force=TRUE))
}

pacman::p_load(powerSurvEpi, tidyverse, dplyr, knitr)

```

#Estimate NO2 SD from national model 

Use overall SD (all selected years) for standardized NO2 (per 10 ppb) for all years (including pre 1994)

```{r}
#no2 (ppb) national model predictions
no2 <- read.csv(file.path("Data", "PowerCalculation", "ACT_Historical_NO2_tr0062.csv"))

#only keep data for King county (start with 53033) or ?Snohomish County (starts with 53061) 
no2 <- no2 %>% filter(substr(tract_key,1,5)==53033 | substr(tract_key,1,5)==53061) 

#ppb stanardization
standardize <- 10

#calculate SD for 10 ppb of NO2
hx_no2_sd <- round(sd(as.matrix(no2[-c(1)])/standardize), 2)

 
#NO2 quantiles 
#hx_no2_quantiles <- round(quantile(as.matrix(no2[-c(1:5)]), c(0, 0.25, 0.5, 0.75, 1)), 1)     

```

# adjust national estimate variability to what we expect to see using the city-specific spatiotemporal estimates we will be using

```{r}
#take the ratio of SD we see for city-specific spatiotemporal (ST) models to the SD we see for national ST model. 

#Data from Micheal Young and Kirwa Kipruto 5/22/2019. ?Unpublished Keller 2015 data?
baltimore <- 5.6/4.4
ny <- 8.7/6.8
la <-9.8/6.6
windston.salem <-4.0/3.6
chicago <-  6.2/4.0
saint.paul <- 4.1/3.6
# these are ratios of SPIROMICS/National model estimates
# sf <- 6.2/5.1
# ann.arbor <-4.2/5.0
# salt.lake.city <- 8.9/5.2

city.specific.to.national.SD <- data.frame(city=c("Baltimore", "NY", "LA", "Windston-Salem", "Chicago", "Saint Paul"), SD_ratio = c(baltimore, ny, la, windston.salem, chicago, saint.paul)  )

```

```{r}
#NO2 SD we expect to see for 10 ppb from the city-specific ST model estimates
adj.no2.sd.range <- round(hx_no2_sd*range(city.specific.to.national.SD$SD_ratio),2) #0.58, 0.81

```

#power calculation

```{r}
#Power Calculation for Cox Proportional Hazards Regression with Nonbinary Covariates for Epidemiological Studies https://cran.r-project.org/web/packages/powerSurvEpi/powerSurvEpi.pdf 

#Data from Roy Pardee from latest freeze as of 5/22/2019
n.events = 1270             
n.participants = 5546        

alpha = 0.05   # or 0.1?? this uses a 1-sided test...?
sds <- seq(adj.no2.sd.range[1], adj.no2.sd.range[2], by = 0.01)

hr = rep(seq(1.05, 1.50, by = 0.01), each=length(sds))

rho2=0 #assume 0 correlation between covariate of interest and other covariates"

power.df <- data.frame(SD = rep(sds, length(unique(hr))), HR = hr, Power=NA)

for (i in 1:nrow(power.df)) {
  #i=1
  power.df[i,"Power"] <- round(powerEpiCont.default(n=n.participants, theta = power.df$HR[i], sigma2 = power.df$SD[i]^2, psi=(n.events/n.participants), rho2 = rho2, alpha = alpha), 2)
    }

#select SDs & HRs with power ~ 0.80 
# df2 <- power.df %>% filter(Power >= 0.70 & Power < 1.0) %>%
#   group_by(HR) #%>% filter(Power == min(Power))

df <- power.df %>% filter(Power >= 0.80 & Power < 1.0) %>%
  group_by(HR) %>% filter(Power == min(Power))

  
```






 





 