---
title: "test code"
author: "Magali Blanco"
date: "4/18/2019"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, 
                      cache=F, cache.comments = F, 
                      message = F, warning = F, 
                      tidy.opts=list(width.cutoff=60), tidy=TRUE,
                      fig.height = 5, fig.width = 8
                      ) 

rm(list = ls(all = TRUE))

pacman::p_load(knitr, kableExtra, 
               #descriptive statistics
               Hmisc, EnvStats, 
               # modeling
               #pls, geoR, #gstat - alternative for UK
               #akima, # interp() - interpolate predictions on map
               ggpubr, tidyverse,
               # 3D mapping
               rayshader,
               
               #parallel  # mclapply() for parallized processing;  detectCores()
               )    
```

```{r}

data.frame(
  a = c(1,2,3),
  b = c(1,2,3)
) %>% 
  kable() %>%
  kable_styling()

```

